apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-cli
  template:
    metadata:
      labels:
        app: pokedex-cli
    spec:
      containers:
        - name: pokedex-cli
          image: yengso/pokedex-cli:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"