name: App Deployment

on:
  workflow_run:
    workflows: ["Docker build and push image"]
    types:
      - completed
    branches:
      - main

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Get Short sha
        id: sha
        run: echo "short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Update image tags
        run: |
          yq eval '.spec.template.spec.containers[0].image = "yengso/pokedex-cli:${{ steps.sha.outputs.short }}"' -i k8s/base/pokedexcli-deployment.yaml

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add k8s/base/pokedexcli-deployment.yaml
          git commit -m "chore: update image to ${{ steps.sha.outputs.short }}"
          git push
















